### PR TITLE
680 add image url in survey

### LINKED ISSUE #680: Add image_url in survey
- [ ] Add image_url in survey model;
- [ ] Add image_url in JSON's Survey;
- [ ] Add image_url in swagger;
- [ ] Add image_url in survey dashboard.

### PR DESCRIPTION
**Pull request by philipeleandro**
fix #680 

- [x] Add image_url in survey model;
- [x] Add image_url in JSON's Survey;
- [x] Add image_url in swagger;
- [x] Add image_url in survey dashboard.

@PolinaStamenova @edimossilva

### CODE REVIEW

**Review by edimossilva — APPROVED** [review]

**Review by PolinaStamenova — APPROVED** [review]
Nice, nice 🎉

**Review by PolinaStamenova — CHANGES_REQUESTED** [review]

**Comment by philipeleandro** [comment]
@PolinaStamenova I've tried this way. Tell me if it is a good change.

**Review by edimossilva — APPROVED** [review]

**Comment by PolinaStamenova** [comment]
> @PolinaStamenova I've tried this way. Tell me if it is a good change.

It is okay. But you can also use the `before` method
```
before { visit admin_survey_path(survey1) }
```
It will execute the code in the ` {} ` before each test.  You can write something like that:

```
describe 'show' do 
  before { visit admin_survey_path(survey1) }

  it 'can see his own image_url' do
     expect(page).to have_text(survey1.image_url)
  end

  it "can't see image_url that not belongs to him" do
     expect(page).not_to have_text(survey2.icon_url)
  end
end
```



@philipeleandro if you want we can arrange a meeting and I can explain you about it.

**Comment by philipeleandro** [comment]
@PolinaStamenova Let's schedule a call this week to you explain me. :)

**Comment by PolinaStamenova** [comment]
> @PolinaStamenova Let's schedule a call this week to you explain me. :)

**Comment by PolinaStamenova** [comment]
> @PolinaStamenova Let's schedule a call this week to you explain me. :)

Good

**Review by edimossilva — APPROVED** [review]
Nice!!!

**Pull request merged**
