### PR TITLE
🔨 refactor: add handle to error message to user #396

### LINKED ISSUE #396: Handle error messages
When starting a survey I verified that a technical error is returned to the user, it is necessary to change it to the message returned from the back.

### PR DESCRIPTION
**Pull request by iurynogueira**
fix #396 

Handle error message.

### CODE REVIEW

**Review by edimossilva — APPROVED** [review]
LGTM

**Review by edimossilva — COMMENTED** [review]
Tests?

**Comment by iurynogueira** [comment]
> forget about the tests

Now we have full coverage in error handler. 
I cant forget of tests 😃 


print

**Comment by edimossilva** [comment]
> > forget about the tests
> 
> Now we have full coverage in error handler. 
> I cant forget of tests 😃 
> 
> 
> print
> 
> 

That is what make me happy!!!!
Congrats!

**Pull request merged**
