### PR TITLE
547 - Adding survey progress

### LINKED ISSUE #547: Add progress bar to answering question flow
While User is answering many questions from a survey the user should know how far he is from finishing the survey

### PR DESCRIPTION
**Pull request by andersonmalheiro**
fix #547

# Adding survey progress

#### Only select the appropriate.

- [ ] **Model testing.**
- [ ] **Request testing and swagger doc update.**
- [x] **System testing.**
- [ ] **No tests required.**

### CODE REVIEW

**Review by edimossilva — APPROVED** [review]
Nice!

**Review by iurynogueira — APPROVED** [review]

**Comment by andersonmalheiro** [comment]
@edimossilva @iurynogueira,
I needed to make some extra changes due to the new codeclimate rules, so I had to make some changes to files outside the scope of the task. Review it again, please.

**Comment by andersonmalheiro** [comment]
@iurynogueira I had to change the survey test structure because in some cases the mocked data was being changed in a unexpected way and it was causing some errors on new tests.

**Review by edimossilva — APPROVED** [review]
LGTM
Nice work!

**Review by iurynogueira — APPROVED** [review]
Great!

**Pull request merged**
