### PR TITLE
Change almost all of the hard coded paths to rails helper paths

### LINKED ISSUE #149: use rails helper methods for paths instead of hard coded paths
example: Use `api_v1_users_path` instead of `api/v1/users`, refactor all urls in the specs

### PR DESCRIPTION
**Pull request by garciajordy**
# Paths

**Rspec:**
- Change almost all paths from hard-coded to rails helper paths.
- Change for example from "user.id" to "user" in rails helper paths.

**Nice to have:**
- spec/requests/surveys_request_spec.rb:60, A better way how to write this api_v1_surveys_path << "?user_id=#{another_user.id}"

_Thanks for taking the time to review my PR_ 😄 

fix #149

### CODE REVIEW

**Review by edimossilva — COMMENTED** [review]
Hi @garciajordy , congratulation on the PR, very organized.

LGTM, I will approve and merge after you improve that "nice to have" you mentioned. You can do like => `api_v1_surveys_path(user_id: another_user.id)`

**Comment by edimossilva** [comment]
> Hi @garciajordy , congratulation on the PR, very organized.
> 
> LGTM, I will approve and merge after you improve that "nice to have" you mentioned. You can do like => `api_v1_surveys_path(user_id: another_user.id)`

btw, the issue `https://github.com/espoo-dev/espoo-dev/issues/149` is not linked to the project, can you do it as well?
If we forget to link they will not show up on demo.

**Comment by garciajordy** [comment]
image

**Comment by garciajordy** [comment]
image

Not sure why it's not showing on your browser. You can also see in the PR description that I wrote fix #149

**Comment by edimossilva** [comment]
@garciajordy this `PR` is linked to the `issue`, but the `issue` is not linked to the `project`
image

**Comment by garciajordy** [comment]
> @garciajordy this `PR` is linked to the `issue`, but the `issue` is not linked to the `project`
> image

Thanks for showing me! I will do this for all the upcoming issues!

**Comment by edimossilva** [comment]
@garciajordy currently github allows users to link `PRs` and `issues` to `project`, you linked the `PR` to the `project` but you should have linked the `issue` to the `project`.  I did the prooper links this time.

Why do we link issues instead of PR?
Just a particular choice

**Review by edimossilva — APPROVED** [review]

**Pull request merged**
