### PR TITLE
Adds refresh button on surveys page

### LINKED ISSUE #430: Add refresh button on surveys page
Add a button that when clicked call the api again.

`https://espoolingo.herokuapp.com/surveys`

### PR DESCRIPTION
**Pull request by mizek1**
fix #430 

# Adds refresh button on surveys page

####

- [ ] **Model testing.**
- [ ] **Request testing.**
- [ ] **System testing.**
- [X] **No tests required.**

### CODE REVIEW

**Review by edimossilva — COMMENTED** [review]
Hi @mizek1 , I am not sure why tests are not required here, could you explain to me please?

**Comment by mizek1** [comment]
> Hi @mizek1 , I am not sure why tests are not required here, could you explain to me please?

I don't know how to fill the pull request form properly yet, sorry 😭 
Also, this page (survey) doesn't have any tests yet, should I add them in this issue or we can open a new one? @edimossilva

**Comment by edimossilva** [comment]
> > Hi @mizek1 , I am not sure why tests are not required here, could you explain to me please?
> 
> I don't know how to fill the pull request form properly yet, sorry 😭 
> Also, this page (survey) doesn't have any tests yet, should I add them in this issue or we can open a new one? @edimossilva 

@mizek1, no need for sorry. It is a shame that we have no tests for survey.

You can do it in another issue if you prefer this way. Usually my way of thinking is "if there is code, should have test".

Please let me know if you want to do it here or in another PR

**Comment by mizek1** [comment]
> > > Hi @mizek1 , I am not sure why tests are not required here, could you explain to me please?
> > 
> > 
> > I don't know how to fill the pull request form properly yet, sorry 😭
> > Also, this page (survey) doesn't have any tests yet, should I add them in this issue or we can open a new one? @edimossilva
> 
> @mizek1, no need for sorry. It is a shame that we have no tests for survey.
> 
> You can do it in another issue if you prefer this way. Usually my way of thinking is "if there is code, should have test".
> 
> Please let me know if you want to do it here or in another PR

I can do it in another PR @edimossilva! I opened the issue #444 for it.

**Comment by edimossilva** [comment]
> > > > Hi @mizek1 , I am not sure why tests are not required here, could you explain to me please?
> > > 
> > > 
> > > I don't know how to fill the pull request form properly yet, sorry sob
> > > Also, this page (survey) doesn't have any tests yet, should I add them in this issue or we can open a new one? @edimossilva
> > 
> > 
> > @mizek1, no need for sorry. It is a shame that we have no tests for survey.
> > You can do it in another issue if you prefer this way. Usually my way of thinking is "if there is code, should have test".
> > Please let me know if you want to do it here or in another PR
> 
> I can do it in another PR @edimossilva! I opened the issue #444 for it. Can you assign me?

done @mizek1

**Pull request merged**
